server:
  port: 8085

spring:
  application:
    name: devtrace-platform
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/devtrace}
    username: ${SPRING_DATASOURCE_USERNAME:devtrace}
    password: ${SPRING_DATASOURCE_PASSWORD:devtrace}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

devtrace:
  analysis:
    slow-span-threshold-ms: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
